githubproject/lbdd/mainpage/urls.py
from django.urls import path
from django.urls import path
from mainpage import views

urlpatterns = [
    path('',views.main_page,name='main_page'),
]

githubproject/lbdd/urls.py
from django.urls import path
from . import views
 
app_name = 'lbdd'

urlpatterns = [
    path('d3gen/',views.d3gen,name='d3gen'),
    path('amesprediction/',views.amespred,name='property_prediction'),
    path('molfilter/',views.molfilter,name='molecules_filter'),
    path('stringtest/<str:strcha>/',views.strtest,name='strtest'), 
]

githubproject/web_v1/urls.py
#from mainpage.views import main_page
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainpage.urls')),
    path('findtarget',include('findtarget.urls')),
    path('database_test',include('ourdatabase.urls')),
    path('leadopt',include('leadopt.urls')),
    path('fuser-app/',include('fuser.urls')),
    path('admet/',include('admet.urls')),
    path('chemblbase/',include('chemblbase.urls')),
    path('drawpic/',include('jsmetest.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('filtercheck/',include('filtercheck.urls')),
    path('lbdd/',include('lbdd.urls')),
    path('docnotes/',include('docnotes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

githubproject/lbdd/mainpage/models.py
from django.db import models

# Create your models here.

githubproject/lbdd/models.py
from pyexpat import model
from django.db import models

# Create your models here.

class PropertyDocument(models.Model):
    docfile = models.FileField()

class FilterDocument(models.Model):
    passed_file = models.FileField()
    error_file = models.FileField()

githubproject/lbdd/forms.py
from django import forms

CHIRALITY_SOURCE_TYPE=[
    ('Keep','Keep'),
    ('Enumerate','Enumerate'),
]

CONFORMATION_TYPE=[
    ('2D','2D'),
    ('3D','3D'),
] 

class ConfGenForm(forms.Form):
    chirality_source = forms.CharField(label='Enumerate chirality or not ?', widget=forms.Select(choices=CHIRALITY_SOURCE_TYPE))
    conf_type = forms.CharField(label='2D or 3D', widget=forms.Select(choices=CONFORMATION_TYPE))
    docfile = forms.FileField(label='Select a sdf file')

CHEMPROP_TYPE=[
    ('Train','Train'),
    ('Predict','Predict'),
]

class AmesForm(forms.Form):
    docfile = forms.FileField(label='Select a file',required=False)
    compounds = forms.CharField(widget=forms.Textarea,required=False)

class MolFilterForm(forms.Form):
    docfile = forms.FileField(label='Select a file',required=True)
    

githubproject/lbdd/mainpage/views.py
from django.shortcuts import render

# Create your views here.
def main_page(request):
    return render(request,'mainpage.html',{})

githubproject/lbdd/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, StreamingHttpResponse
from rdkit import Chem
from rdkit.Chem import PandasTools, AllChem
import pandas as pd
import os,subprocess
import time
import logging

from web_v1.settings import JXYTEMPDIR, AMESDIR, MEDIA_ROOT, AMESDIR_DIR, HOBDIR
from .conformation_gen import d3confgen
from .hobpre import hobmodel_predict
from .forms import AmesForm, ConfGenForm, MolFilterForm
from .models import PropertyDocument,FilterDocument
from .mfilter import standardize

def molfilter(request):
    if request.method == 'POST':
        form = MolFilterForm(request.POST,request.FILES)
        if form.is_valid():
            fname = request.FILES['docfile']
            current_time = time.strftime("%Y%m%d-%H%M%S")
            tempfilename = JXYTEMPDIR + request.user.username + current_time +'.bak'
            with open(tempfilename,'wb+') as destination:
                for chunk in fname.chunks():
                    destination.write(chunk)
            df = pd.read_csv(tempfilename,header=None,usecols=[0],sep='\t')
            smiles_list = []
            for i in range(len(df)):
                smi = df.iloc[i][0]
                if not pd.isnull(smi):
                    smiles_list.append(smi)
            logger = logging.getLogger("django")
            logger.info(len(smiles_list))

            exportfile_x,errorfile_x = standardize(request.user.username,smiles_list)             
            newfile = FilterDocument(passed_file=exportfile_x,error_file=errorfile_x)
            newfile.save()
            dfile = FilterDocument.objects.get(passed_file=exportfile_x,error_file=errorfile_x)
            return render(request,'lbdd/mfilter.html',{'form':form, 'dfile':dfile})

    else:
        form = MolFilterForm()
        return render(request,'lbdd/mfilter.html',{'form':form,'dfile':[]}) 


def amespred(request):
    if request.method == 'POST':
        form = AmesForm(request.POST,request.FILES)
        smiles = []
        if form.is_valid():
            textaaa = form.cleaned_data['compounds']
            if textaaa:
                testaaa_list = textaaa.split()
                for smi in testaaa_list:
                    smiles.append(smi)
            else:
                logger = logging.getLogger("django")
                logger.info("no input in textarea")
            if not request.FILES:
                logger = logging.getLogger("django")
                logger.info("no file given")
            else:
                fname = request.FILES['docfile']
                current_time =  time.strftime("%Y%m%d-%H%M%S")
                tempfilename = JXYTEMPDIR + request.user.username + current_time +'.bak'
                with open(tempfilename,'wb+') as destination:
                    for chunk in fname.chunks():
                        destination.write(chunk)
                
                df = pd.read_csv(tempfilename)
                label_name = df.columns[0]
                logger = logging.getLogger("django")
                logger.info(os.getcwd())
                logger.info(AMESDIR)
                for index,smi in df.iterrows():
                    logger.info(smi[label_name])
                    smiles.append(smi[label_name])

        df_hob = hobmodel_predict(smiles,HOBDIR)
        logger.info(df_hob)

        df_predict = pd.DataFrame({'SMILES':smiles})
        current_time =  time.strftime("%Y%m%d-%H%M%S")
        tempfilename_input   = JXYTEMPDIR + request.user.username + current_time +'.input'
        tempfilename         = 'ames_results/' + request.user.username + current_time +'.csv'
        tempfilename_output  = JXYTEMPDIR + request.user.username + current_time +'.output'
        tempfilename_results = os.path.join(MEDIA_ROOT,tempfilename) 
        df_predict.to_csv(tempfilename_input,index=False)
        subprocess.run(["chemprop_predict","--test_path",tempfilename_input,"--checkpoint_dir",AMESDIR,"--preds_path",tempfilename_output]) 

        ames_results = pd.read_csv(tempfilename_output)
        ames_results.insert(2,'hob',df_hob[:,1].tolist())
        ames_results_sort = ames_results.sort_values('Label')
        PandasTools.AddMoleculeColumnToFrame(ames_results_sort,'SMILES','Molecule')
        PandasTools.SaveXlsxFromFrame(ames_results_sort,tempfilename_results,molCol='Molecule')

        ames_results_dic = ames_results.to_dict('records')
        #contend={'ames_results':ames_results}
        #for lig in ames_results_dic:
        #    logger.info(lig.get("SMILES"))
        newdoc = PropertyDocument(docfile = tempfilename)
        newdoc.save()
        dfile = PropertyDocument.objects.get(docfile=tempfilename)
        #return HttpResponse('Hello Mr.Jia')
        return render(request,'lbdd/property.html',{'form':form,'ames_results_dic':ames_results_dic,'dfile':dfile})
    else:
        form = AmesForm()
        #content={}
        return render(request,'lbdd/property.html',{'form':form,'ames_results':[],'dfile':[]})
    #return HttpResponse('Hello Mr.Jia')

# Create your views here.
def d3gen(request):
    if request.method == 'POST':
        form = ConfGenForm(request.POST,request.FILES)
        if form.is_valid():
            chi_type  = form.cleaned_data['chirality_source']
            conf_type = form.cleaned_data['conf_type'] 

            fname = request.FILES['docfile']
            current_time =  time.strftime("%Y%m%d-%H%M%S")
            tempfilename = JXYTEMPDIR + request.user.username + current_time +'.bak'
            with open(tempfilename,'wb+') as destination:
                for chunk in fname.chunks():
                    destination.write(chunk)

            mols = Chem.SDMolSupplier(tempfilename)
            exportfile,exportfile_x = d3confgen(request.user.username,mols,chi_type,conf_type)

            try:
                response = StreamingHttpResponse(open(exportfile,'rb'))
                response['content_type'] = "application/octet-stream"
                response['Content-Disposition'] = 'attachment; filename=' + exportfile_x
                return response
            except Exception:
                return Http404

    else:
        form = ConfGenForm()
        return render(request,'lbdd/d3gen.html',{'form':form})

def strtest(request,strcha):
    return HttpResponse(strcha)

githubproject/lbdd/templates/lbdd/d3gen.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block title %}小分子三维构象生成{% endblock %}

{% block css %}
 <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        小分子三维构象生成
        <small>测试版</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">小分子三维构象生成</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <!-- Main content -->

    <form action="{% url 'lbdd:d3gen' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        <p>{{ form.non_field_errors }}</p>
        <P class="fieldWrapper">
          {{ form.conf_type.errors }}
          {{ form.conf_type|as_crispy_field }}
        </P>
        <P class="fieldWrapper">
          {{ form.chirality_source.errors }}
          {{ form.chirality_source|as_crispy_field }}
        </P>
        <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
        <p>
            {{ form.docfile.errors }}
            {{ form.docfile }} 
        </p>
        <p><input type="submit" value="Generation" /></p>
    </form>

    <!-- /.content -->
{% endblock %}

githubproject/lbdd/templates/lbdd/mfilter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block title %}分子过滤{% endblock %}

{% block css %}
 <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        分子过滤
        <small>测试版</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">分子过滤</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <!-- Main content -->

    <form action="{% url 'lbdd:molecules_filter' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
        <p>
            {{ form.docfile.errors }}
            {{ form.docfile }}
        </p>
        <p><input type="submit" value="Filter" /></p>
    </form>
    {% if dfile %}
    <a href="{{dfile.passed_file.url}}"><button class="btn btn-default btn-md">Download Filtered </button></a>
    <a href="{{dfile.error_file.url}}"><button class="btn btn-default btn-md">Download Error Smiles</button></a>
    {% else %}

    {% endif %}
    <!-- /.content -->
{% endblock %}

githubproject/lbdd/templates/lbdd/property.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block title %}化合物性质预测{% endblock %}

{% block css %}
 <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        化合物性质预测
        <small>测试版</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">化合物性质预测</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <!-- Main content -->

    <form action="{% url 'lbdd:property_prediction' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <P class="fieldWrapper">
          {{ form.compounds.errors }}
          {{ form.compounds|as_crispy_field }}
        </P>
        <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
        <p>
            {{ form.docfile.errors }}
            {{ form.docfile }}
        </p>
        <p><input type="submit" value="Predict" /></p>
    </form>
    {% if ames_results_dic %}
    <a href="{{dfile.docfile.url}}"><button class="btn btn-default btn-md">Download Predictions</button></a>
    {% for compound in ames_results_dic %}
    <p>SMILES: {{compound.SMILES}}</p>            
    <p>AMES: {{compound.Label}}</p>
    <p>HOB: {{compound.hob}}</p>
    <hr>
    {% endfor %} 
    {% else %}

    {% endif %}
    <!-- /.content -->
{% endblock %}

githubproject/lbdd/templates/lbdd/property2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block title %}化合物性质预测{% endblock %}

{% block css %}
 <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        化合物性质预测
        <small>测试版</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">化合物性质预测</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <!-- Main content -->

    <form action="{% url 'lbdd:property_prediction' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <P class="fieldWrapper">
          {{ form.compounds.errors }}
          {{ form.compounds|as_crispy_field }}
        </P>
        <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
        <p>
            {{ form.docfile.errors }}
            {{ form.docfile }}
        </p>
        <p><input type="submit" value="Predict" /></p>
    </form>
    
    {% for compound in ames_results_dic %}
    <p>SMILES: {{compound.SMILES}}</p>            
    <p>Label: {{compound.Label}}</p>
    <hr>
    {% endfor %} 
    <!-- /.content -->
{% endblock %}