githubproject/chemblbase/urls.py
from django.urls import path
from . import views
 
app_name = 'chemblbase'
 
urlpatterns = [
    path('', views.chemblmainpage, name='chemblmainpage'),
    path('compound/',views.compound,name='dashboard'),
    path('index/<int:kinase_id>',views.index,name='index'),
    path('kinase/',views.allkinase,name='kinase'),
    path('singlemolecule/<str:chemblid>',views.singlemolecule,name='singlemolecule'),
    path('singlemoleculeosri/<str:chemblid>',views.singlemoleculeosri,name='singlemoleculeosri'),
    path('contact/',views.get_contact,name='contact'),
    path('addmol/',views.get_mol,name='addmol'),
    path('addmol/thanks',views.showthanks,name='showthanks'),
    path('drawmolecule/',views.drawmolecule,name='drawmolecule'),
    path('inhousecompound/',views.showinhouse,name='inhousecompound'),
    path('jme_window/',views.jmewindow,name='jme_window'),
    path('substrcuture_search',views.substructure_search,name='substructure_search'),
    path('substructure_search/results',views.substructure_search_results,name='substructure_search_results'),
    path('fileupload/',views.uploadfile,name='uploadfile'),
    path('delmol/',views.delmol,name='delmol'),
    path('editmol/',views.editmol,name='editmol'),
    path('asinhouse/',views.as_inhouse,name='asinhouse'),
    path('adsearch/',views.ad_search,name='adsearch'),
    path('exportfile/',views.exportfile,name='exportfile'),
] 

githubproject/lbdd/mainpage/urls.py
from django.urls import path
from django.urls import path
from mainpage import views

urlpatterns = [
    path('',views.main_page,name='main_page'),
]

githubproject/lbdd/urls.py
from django.urls import path
from . import views
 
app_name = 'lbdd'

urlpatterns = [
    path('d3gen/',views.d3gen,name='d3gen'),
    path('amesprediction/',views.amespred,name='property_prediction'),
    path('molfilter/',views.molfilter,name='molecules_filter'),
    path('stringtest/<str:strcha>/',views.strtest,name='strtest'), 
]

githubproject/mainpage/urls.py
from django.urls import path
from django.urls import path
from mainpage import views

urlpatterns = [
    path('',views.main_page,name='main_page'),
]

githubproject/web_v1/urls.py
#from mainpage.views import main_page
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainpage.urls')),
    path('findtarget',include('findtarget.urls')),
    path('database_test',include('ourdatabase.urls')),
    path('leadopt',include('leadopt.urls')),
    path('fuser-app/',include('fuser.urls')),
    path('admet/',include('admet.urls')),
    path('chemblbase/',include('chemblbase.urls')),
    path('drawpic/',include('jsmetest.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('filtercheck/',include('filtercheck.urls')),
    path('lbdd/',include('lbdd.urls')),
    path('docnotes/',include('docnotes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

githubproject/lbdd/mainpage/models.py
from django.db import models

# Create your models here.

githubproject/mainpage/models.py
from django.db import models

# Create your models here.

githubproject/lbdd/mainpage/views.py
from django.shortcuts import render

# Create your views here.
def main_page(request):
    return render(request,'mainpage.html',{})

githubproject/mainpage/views.py
from django.shortcuts import render

# Create your views here.
def main_page(request):
    return render(request,'mainpage.html',{})

githubproject/lbdd/mainpage/templates/mainpage.html
<!DOCTYPE HTML>
{% load static %}
<!--
	Halcyonic by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)

    Group introductions 
	Owner: Xiangyu Jia
    Time: 2021.06.04 
-->
<html>
	<head>
		<title>AIDD</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />

	</head>

	<body>
		<div id="page-wrapper">

			<!-- Header -->
				<section id="header">
					<div class="container">
						<div class="row">
							<div class="col-12">

								<!-- Logo -->
									<h1><a href="mainpage.html" id="logo">AIDD in OTSUKA</a></h1>

								<!-- Nav -->
									<nav id="nav">
										<a href="mainpage.html">HOME</a>
										<a href="mainpage.html">People</a>
										<a href="mainpage.html">Research</a>
										<!--a href="mainpage.html">Education</a-->
										<a href="mainpage.html">Publications</a> 
										<a href="{% url 'chemblbase:chemblmainpage' %}">Database</a>  
										<!--a href="mainpage.html">Contact Me</a-->

	
											{% if user.is_authenticated %}
											  <a>User: {{ user.get_username }}</a>
											  <a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
											{% else %}
											  <a href="{% url 'login'%}?next={{request.path}}">Login</a>
											{% endif %} 
										

							</div>
						</div>
					</div>
					<div id="banner">
						<div class="container">
							<div class="row">
								<div class="col-1 col-12-medium">
									<!--<p style="font-size:25px"> 
										We do something really useful, important, and unique. Learn all about it  <a href="Research.html">Here...</a>
									</p>
										<a href="Research.html" class="button-large" style="font-size:15px">Go on, click me!</a>
									<a href="#" class="bordered-feature-image"><img src="images/pic06.jpg" alt="" /></a>-->
								</div>
								<div class="col-10 col-12-medium imp-medium">

									<!-- Banner Image -->
									<!--a href="#" class="bordered-feature-image"><img src="images/the_main_process.png" alt="" /></a-->
									<a href="#" class="bordered-feature-image"><img src="{% static 'images/the_main_process.png' %}" alt="" /></a>
							
								</div>
								<div class="col-1 col-12-medium">
									<!--<p style="font-size:25px"> 
										We do something really useful, important, and unique. Learn all about it  <a href="Research.html">Here...</a>
									</p>
										<a href="Research.html" class="button-large" style="font-size:15px">Go on, click me!</a>
									<a href="#" class="bordered-feature-image"><img src="images/pic06.jpg" alt="" /></a>-->
								</div>
							</div>
						</div>
					</div>
				</section>

			<!-- Features -->
				<section id="features">
					<div class="container">
						<div class="row">
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #1 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'images/find_target_1.png' %}"  /></a>
										<h2>Target Prediction</h2>
										<p>
											Based on the ChEMBL data, a deep learning model is trained to predict the target.
											<a href="{% url 'find_target' %}">More</a>
										</p>
									</section>

							</div>
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #2 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'images/leadopt.png' %}" /></a>
										<h2>Lead Optimization</h2>
										<p>
											A deep convolutional neural network is trained to predict appropriate fragments given the structure of a receptor/ligand complex. 
											<a href="{% url 'leadopt' %}">More</a>
										</p>
									</section>

							</div>
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #3 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'images/pro_seq.png' %}"  /></a>
										<h2>Tr-Rosetta</h2>
										<p>
											An algotithm for fast and accurate protein structure prediction. It builts the protein based on direct energy minimization with a restrained Rosetta.
											<a href="https://yanglab.nankai.edu.cn/trRosetta/">More</a> 
										</p>
									</section>

							</div>
							<div class="col-3 col-6-medium col-12-small">

								<!-- Feature #4 -->
									<section>
										<a href="#" class="bordered-feature-image"><img src="{% static 'images/smile.png' %}" alt="" Width="120" Height="120" /></a>
										<h2>Free Energy Perturbation</h2>
										<p>
											A ultrabroad discrete or supercontinuum XUV spectrum can be generated.  
											<a href="https://www.cresset-group.com/about/news/fep-drug-discovery-toolbox/">More</a>
										</p>
									</section>

							</div>
						</div>
					</div>
				</section> 

			<!-- Content -->
				<section id="content">
					<div class="container">
						<div class="row aln-center">
							<div class="col-4 col-12-medium">

								<!-- Box #1 -->
									<section>
										<header>
											<h2>AIDD</h2>
											<h3>Artificial Intelligence Drug Design</h3>
										</header>
										<ul class="quote-list">
											<li>
												<img src="{% static 'images/smile.png' %}" alt="" Width="120" Height="120"/>
												<!--<p>"LASER"</p>-->
												<span>EVOLVING DRUG DISCOVERY.</span>
											</li>
											
										</ul>
									</section>

							</div>
							<div class="col-4 col-6-medium col-12-small">

								<!-- Box #2 -->
									<section>
										<header>
											<h2>What We Do</h2>
											<h3>DRUG DISCOVERY.</h3>
										</header>
										<ul class="check-list">
											<li>Find the target</li>
											<li>Predict the binding affinity</li>
											<li>Generate novel molecules</li>
										</ul>
									</section>

							</div>
							<div class="col-4 col-6-medium col-12-small">

								<!-- Box #3 -->
									<section>
										<header>
											<h2>Recent news</h2>
											<h3>Progresses, talks</h3>
										</header>
										<ul class="quote-list">
											<li>
												<img src="{% static 'images/smile.png' %}" alt="" Width="120" Height="120" />
												<p>"Ml in DFT"</p>
												<span>Dr. Zhiming Li and Dr. Guoliang Song, Fudan, Shanghai, China</span>
											</li>
											<li>
												<img src="{% static 'images/smile.png' %}" alt="" Width="120" Height="120" />
												<p>"DC-MBAR"</p>
												<span>Dr. Xiangyu Jia</span>
											</li>
											<!--<li>
												<img src="images/pic08.jpg" alt="" />
												<p>"High harmonic generations in solids"</p>
												<span>XXX, xxx, yyy, zzz</span>
											</li>-->
										</ul>
									</section>

							</div>
						</div>
					</div>
				</section>

			<!-- Footer
				<section id="footer">
					<div class="container">
						<div class="row">
							<div class="col-12 col-12-medium">
									<section>
										<h2>International Groups</h2>
										<div>
											<div class="row">
												<div class="col-2 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">1.0</a></li>
														<li><a href="#">1.0</a></li>
														<li><a href="#">1.0</a></li>
														<li><a href="#">1.0</a></li>
													</ul>
												</div>
												<div class="col-2 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">2.0 </a></li>
														<li><a href="#">2.0</a></li>
														<li><a href="#">3.0</a></li>
														<li><a href="#">4.0</a></li>
													</ul>
												</div>
												<div class="col-2 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">5.0</a></li>
														<li><a href="#">6.0</a></li>
														<li><a href="#">7.0</a></li>
														<li><a href="#">8.0</a></li>
													</ul>
												</div>
												<div class="col-2 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">9.0</a></li>
														<li><a href="#">10.0</a></li>
														<li><a href="#">11.0</a></li>
														<li><a href="#">12.0</a></li>
													</ul>
												</div>
												<div class="col-2 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">9.0</a></li>
														<li><a href="#">10.0</a></li>
														<li><a href="#">11.0</a></li>
														<li><a href="#">12.0</a></li>
													</ul>
												</div>
												<div class="col-2 col-12-small">
													<ul class="link-list last-child">
														<li><a href="#">9.0</a></li>
														<li><a href="#">10.0</a></li>
														<li><a href="#">11.0</a></li>
														<li><a href="#">12.0</a></li>
													</ul>
												</div>
											</div>
										</div>
									</section>

							</div>
						</div>
					</div>
				</section>
			-->

			<!-- Copyright -->
				<div id="copyright">
					&copy; AIDD in OTSUKA. Dr. Xiangyu Jia. All rights reserved.
				</div>

		</div>

		<!-- Scripts -->
			<script src="{% static 'assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'assets/js/browser.min.js' %}"></script>
			<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'assets/js/util.js' %}"></script>
			<script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>