githubproject/docnotes/urls.py
from django.urls import path
from . import views
 
app_name = 'docnotes'

urlpatterns = [
    path('blog_list/',views.myblog_list,name='blog_list'),
    path('blog_detail/<slug:slug>/',views.myblog_detail,name='blog_detail'),
    path('blog_tex/',views.tex_test,name='tex_text'),
    path('blog_stability/',views.stability,name='stability'),
    path('blog_tnik/',views.tnik,name='tnik'),
    path('blog_vae/',views.vae,name='vae'),
    path('blog_nlrp3/',views.nlrp3,name='nlrp3'),
]

githubproject/lbdd/urls.py
from django.urls import path
from . import views
 
app_name = 'lbdd'

urlpatterns = [
    path('d3gen/',views.d3gen,name='d3gen'),
    path('amesprediction/',views.amespred,name='property_prediction'),
    path('molfilter/',views.molfilter,name='molecules_filter'),
    path('stringtest/<str:strcha>/',views.strtest,name='strtest'), 
]

githubproject/web_v1/urls.py
#from mainpage.views import main_page
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainpage.urls')),
    path('findtarget',include('findtarget.urls')),
    path('database_test',include('ourdatabase.urls')),
    path('leadopt',include('leadopt.urls')),
    path('fuser-app/',include('fuser.urls')),
    path('admet/',include('admet.urls')),
    path('chemblbase/',include('chemblbase.urls')),
    path('drawpic/',include('jsmetest.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('filtercheck/',include('filtercheck.urls')),
    path('lbdd/',include('lbdd.urls')),
    path('docnotes/',include('docnotes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

githubproject/docnotes/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200,unique=True)
    slug = models.SlugField(max_length=200,unique=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS,default=0)
    url = models.URLField(blank=True, null=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

githubproject/docnotes/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import Post
from django_tex.shortcuts import render_to_pdf
# Create your views here.

def myblog_list(request):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    return render(request,'docnotes/list.html',{'queryset':queryset})

def myblog_detail(request,slug):
    model = Post.objects.get(slug=slug)
    return render(request,'docnotes/detail.html',{'model':model})

def tex_test(request):
    template_name = 'docnotes/text.tex'
    content = {'foo':'Bar'}
    return render_to_pdf(request,template_name,content,filename='test.pdf')

def stability(request):
    template_name = 'docnotes/stability.tex'
    return render_to_pdf(request,template_name,{},filename='stability.pdf')

def tnik(request):
    template_name = 'docnotes/tnik.tex'
    return render_to_pdf(request,template_name,{},filename='tnik.pdf')

def vae(request):
    template_name = 'docnotes/vae.tex'
    return render_to_pdf(request,template_name,{},filename='vae.pdf')

def nlrp3(request):
    template_name = 'docnotes/nlrp3.tex'
    return render_to_pdf(request,template_name,{},filename='nlrp3.pdf')

githubproject/docnotes/templates/docnotes/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block title %}小分子三维构象生成{% endblock %}

{% block css %}
 <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        学习文档
        <small>测试版</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">学习文档</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <!-- Main content -->
    <div class="container">
      <div class="row">
        <!--div class="col-md-8 card mb-4  mt-3 left  top"-->
        <div class="col-md-8 top">
          <div class="card-body">
            <h1>{{ model.title }} </h1>
            <p class=" text-muted">{{ model.author }} | {{ model.created_on }}</p>
            <p class="card-text ">{{ model.content | safe | linebreaks }}</p>
          </div>
        </div>

      </div>
    </div>
    <!-- /.content -->
{% endblock %}

githubproject/docnotes/templates/docnotes/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% load static %}
{% block title %}小分子三维构象生成{% endblock %}

{% block css %}
 <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        学习文档
        <small>测试版</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">学习文档</li>
      </ol>
    </section>
{% endblock %}

{% block content %}
    <!-- Main content -->
    <div class="container">
      <div class="row">
          <!-- Blog Entries Column -->
          <div class="col-md-8 mt-3 left">
              {% for post in queryset %}
              <div class="card mb-4">
                  <div class="card-body">
                      <h2 class="card-title">{{ post.title }}</h2>
                      <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                      <p class="card-text">{{post.content|slice:":200" }}</p>
                      <!--a href="{% url 'docnotes:blog_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a-->
                      <a href="{{ post.url }}" class="btn btn-primary">Read More &rarr;</a>
                  </div>
              </div>
              {% endfor %}
          </div>

      </div>
  </div>
    <!-- /.content -->
{% endblock %}